
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.75.221:3306/CAT?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: xjy
    password: 123456
